_core:
  default_config_hash: 68A3PDsSIoX2q7iFOa2lMdnYkgKgem4uh1_RBxcRVWU
report-only:
  enable: true
  directives:
    script-src:
      base: self
      sources:
        - 'https://*.bhashini.co.in'
        - 'https://*.googleapis.com'
        - 'https://*.gstatic.com'
        - 'https://*.google.com'
    style-src:
      base: self
      flags:
        - unsafe-inline
      sources:
        - 'https://*.bhashini.co.in'
        - 'https://*.googleapis.com'
        - 'https://cdn.jsdelivr.net'
    connect-src:
      base: self
      sources:
        - 'https://*.bhashini.co.in'
        - 'https://*.googleapis.com'
        - 'https://*.google.com'
        - 'https://*.gstatic.com'
        - 'https://cdn.jsdelivr.net'
    font-src:
      base: self
      sources:
        - 'https://*.bhashini.co.in'
        - 'https://fonts.gstatic.com'
        - 'https://cdn.jsdelivr.net'
    frame-src:
      base: self
      sources:
        - 'https://*.google.com'
    img-src:
      base: self
      sources:
        - 'data:'
        - 'https://*.bhashini.co.in'
        - 'https://*.gstatic.com'
        - 'https://*.google.com'
  reporting:
    plugin: none
enforce:
  enable: true
  directives:
    script-src:
      base: self
      sources:
        - 'https://*.bhashini.co.in'
        - 'https://*.googleapis.com'
        - 'https://*.gstatic.com'
        - 'https://*.google.com'
    style-src:
      base: self
      flags:
        - unsafe-inline
      sources:
        - 'https://*.bhashini.co.in'
        - 'https://*.googleapis.com'
        - 'https://cdn.jsdelivr.net'
    connect-src:
      base: self
      sources:
        - 'https://*.bhashini.co.in'
        - 'https://*.googleapis.com'
        - 'https://*.google.com'
        - 'https://*.gstatic.com'
        - 'https://cdn.jsdelivr.net'
    font-src:
      base: self
      sources:
        - 'https://*.bhashini.co.in'
        - 'https://fonts.gstatic.com'
        - 'https://cdn.jsdelivr.net'
    frame-src:
      base: self
      sources:
        - 'https://*.google.com'
    img-src:
      base: self
      sources:
        - 'data:'
        - 'https://*.bhashini.co.in'
        - 'https://*.gstatic.com'
        - 'https://*.google.com'
    upgrade-insecure-requests: true
  reporting:
    plugin: none
