login:
  authenticated:
    redirect_url: ''
    allow_destination: false
    weight: 0
  content_editor:
    redirect_url: /admin/content/moderated
    allow_destination: false
    weight: 0
  administrator:
    redirect_url: /admin/dashboard
    allow_destination: false
    weight: 0
  site_admin:
    redirect_url: /admin/dashboard
    allow_destination: false
    weight: 0
  tender_admin:
    redirect_url: /admin/dashboard
    allow_destination: false
    weight: 0
  banner_creator:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  banner_publisher:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  news_creator:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  news_publisher:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  awards_achievements_creator:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  awards_achievements_publisher:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  e_citizen_downloads_creator:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  e_citizen_downloads_publisher:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  awards_achievements_efa_creator:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  awards_achievements_efa_publisher:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  key_profiles_creator:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  key_profiles_publisher:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  career_creator:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  career_pulisher:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  our_units_creator:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  our_units_publisher:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  tenders_creator:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  tenders_publisher:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  notices_creator:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  notices_publisher:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  notifications_creator:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  notifications_publisher:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  photo_gallery_creator:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  photo_gallery_publisher:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  video_gallery_creator:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  video_gallery_publisher:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  related_link_creator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  related_link_publisher:
    redirect_url: ''
    allow_destination: false
    weight: 0
  chatbot_creator:
    redirect_url: /admin/chatbot-question-listing
    allow_destination: false
    weight: 0
  chatbot_publisher:
    redirect_url: /admin/chatbot-question-listing
    allow_destination: false
    weight: 0
  products_services_creator:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
  products_services_publisher:
    redirect_url: /admin/content
    allow_destination: false
    weight: 0
logout:
  authenticated:
    redirect_url: ''
    allow_destination: false
    weight: 0
  content_editor:
    redirect_url: ''
    allow_destination: false
    weight: 0
  administrator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  site_admin:
    redirect_url: ''
    allow_destination: false
    weight: 0
  tender_admin:
    redirect_url: ''
    allow_destination: false
    weight: 0
  banner_creator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  banner_publisher:
    redirect_url: ''
    allow_destination: false
    weight: 0
  news_creator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  news_publisher:
    redirect_url: ''
    allow_destination: false
    weight: 0
  awards_achievements_creator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  awards_achievements_publisher:
    redirect_url: ''
    allow_destination: false
    weight: 0
  e_citizen_downloads_creator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  e_citizen_downloads_publisher:
    redirect_url: ''
    allow_destination: false
    weight: 0
  awards_achievements_efa_creator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  awards_achievements_efa_publisher:
    redirect_url: ''
    allow_destination: false
    weight: 0
  key_profiles_creator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  key_profiles_publisher:
    redirect_url: ''
    allow_destination: false
    weight: 0
  career_creator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  career_pulisher:
    redirect_url: ''
    allow_destination: false
    weight: 0
  our_units_creator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  our_units_publisher:
    redirect_url: ''
    allow_destination: false
    weight: 0
  tenders_creator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  tenders_publisher:
    redirect_url: ''
    allow_destination: false
    weight: 0
  notices_creator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  notices_publisher:
    redirect_url: ''
    allow_destination: false
    weight: 0
  notifications_creator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  notifications_publisher:
    redirect_url: ''
    allow_destination: false
    weight: 0
  photo_gallery_creator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  photo_gallery_publisher:
    redirect_url: ''
    allow_destination: false
    weight: 0
  video_gallery_creator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  video_gallery_publisher:
    redirect_url: ''
    allow_destination: false
    weight: 0
  related_link_creator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  related_link_publisher:
    redirect_url: ''
    allow_destination: false
    weight: 0
  chatbot_creator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  chatbot_publisher:
    redirect_url: ''
    allow_destination: false
    weight: 0
  products_services_creator:
    redirect_url: ''
    allow_destination: false
    weight: 0
  products_services_publisher:
    redirect_url: ''
    allow_destination: false
    weight: 0
