<?php

/**
 * @file
 * Contains general functionality of the module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * Provides additional information about the module.
 */
function foo_captcha_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.foo_captcha':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is a very simple CAPTCHA, which requires users to enter "foo" in a textfield.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_captcha().
 */
function foo_captcha_captcha($op, $captcha_type = '') {
  switch ($op) {
    case 'list':
      return ['Foo CAPTCHA'];

    case 'generate':
      if ($captcha_type == 'Foo CAPTCHA') {
        $captcha = [];
        $captcha['solution'] = 'foo';
        $captcha['form']['captcha_response'] = [
          '#type' => 'textfield',
          '#title' => t('Enter "foo"'),
          '#required' => TRUE,
          '#process' => ['foo_captcha_process'],
          '#cache' => ['max-age' => 0],
        ];
        \Drupal::service('page_cache_kill_switch')->trigger();

        return $captcha;
      }
      break;
  }
}

/**
 * Process the response to the foo CAPTCHA before validation.
 */
function foo_captcha_process($element, $edit) {
  if (\Drupal::config('foo_captcha.settings')->get('foo_captcha_ignore_spaces')) {
    $element['#value'] = preg_replace('/\s*/', '', $element['#value']);
  }
  return $element;
}
