name: 'Admin Audit Trail Config'
type: module
description: 'Logs configuration CUD events performed by the user.'
package: Administration
core_version_requirement: ^10.1 || ^11 || ^12
dependencies:
  - admin_audit_trail:admin_audit_trail

# Information added by Drupal.org packaging script on 2026-08-24
version: '1.0.12'
project: 'admin_audit_trail'
datestamp: 1787579839
