ServerTokens Prod
ServerSignature Off
ServerName localhost
TraceEnable Off

<IfModule mod_headers.c>
  Header always unset X-Powered-By
</IfModule>

<Directory "/opt/drupal/web/files">
  AllowOverride All
  <FilesMatch "\.(php|phar|phtml|pl|py|cgi|asp|aspx|jsp|sh)$">
    Require all denied
  </FilesMatch>
</Directory>
